# Generated by Django 5.1.3 on 2024-11-16 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todomodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='taks_id',
            new_name='task_id',
        ),
    ]
